---
output: html_document
---


```{r setup, include=FALSE}
  library(GADMTools)
  library(plotly)
  library(rosm)
  library(curl)
  library(jsonlite)
  library(magrittr)
  library(tibble)
  library(dplyr)
  library(shiny)
  library(ggplot2)
  library(gganimate)
  library(viridis)
  # Loading country border (level=0 [default])
  # -----------------------------------------------------------------
  ITA <-gadm_sf_loadCountries("ITA",basefile ="./",level=2)
  ITA1 <-gadm_sf_loadCountries("ITA",basefile ="./",level=1)
  par(pin=c(5, 4))
  adige <-gadm_subset(ITA,level=2,regions=c("Bolzano","Trento"))
  #adige <-gadm_subset(ITA,level=1,regions=c( "Bolzano","Trento","Belluno"))
  # BRE2 <-gadm_getBackground(ITA,"ITA","osm")
  
  pcmdpcfr <- read.csv(curl("https://github.com/pcm-dpc/COVID-19/raw/master/dati-regioni/dpc-covid19-ita-regioni.csv"))
  pcmdpcr <- filter(pcmdpcfr,pcmdpcfr$lat > 0 & pcmdpcfr$long >0)
  pcmdpcr$data <- as.Date(as.factor(gsub("T.*","",pcmdpcr$data)))
```

```{r, echo=FALSE,out.width="100%"}
Mapplotr <- plotmap(ITA1)+
    geom_point(pcmdpcr, mapping = aes( x = long , y = lat, size=totale_casi, col = totale_casi, alpha=0.01))+scale_size(range = c(0, 20))+
    transition_states(data,
                      transition_length = 1,
                      state_length = 0.5,wrap = FALSE) +labs(title = "Made with R by Jürgen Mayr, Date:{frame_time}", x="Longitude",y="Latitude",colour="Casi totali") + theme(plot.title = element_text(size=16), legend.text = element_text( size = 16)) + theme(legend.title = element_text( size=16))+ guides(fill = guide_colourbar(barwidth = 2, barheight = 30))+
    scale_color_viridis(option = "D")+
    transition_time(data)
  
  #view_follow(fixed_y = TRUE)
  animate(Mapplotr, height = 1200, width =1200)
  ```