---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
 library(rjson)
library(plotly)
library("openxlsx")
library(leaflet)
library(dplyr)
library(viridis)
library(htmlwidgets)
library(tidyverse)
library(DT)
temp = tempfile(fileext = ".xlsx")
# From http://eric.clst.org/Stuff/USGeoJSON and
# https://en.wikipedia.org/wiki/List_of_United_States_counties_and_county_equivalents
gvcc <- rgdal::readOGR("https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_P_21_municipalities.geojson")
ev <- c(1656,1030,398,14934,778,3505,1755,107739,655,2232,22377,2808,16716,395,8104,2656,5496,2298,6855,1527,2887,5215,3430,2239,665,1378,2389,3351,5384,2823,3579,1000,2629,3311,1726,900,5214,5005,2715,18073,12511,4045,342,1574,1274,5272,3081,2791,841,1692,40862,2914,1701,2086,2017,5869,3230,1973,3937,3825,4869,3783,1565,724,195,1872,3624,546,265,4497,2917,7955,1362,3151,1240,3827,3367,3066,3558,3885,1767,3255,1544,1974,7145,2912,1432,2629,1228,1880,6215,1838,1141,1766,4473,3431,1965,1007,2450,1040,969,2896,1057,3205,3093,6022,2320,3339,4694,959,1597,1875,6979,2998,1389,762)
## OGR data source with driver: GeoJSON 
## Source: "/Users/barret/Documents/git/rstudio/leaflet/leaflet/docs/json/nycounties.geojson", layer: "nycounties"
## with 62 features
## It has 4 fields

# Or use the geojsonio equivalent:
# nycounties <- geojsonio::geojson_read("json/nycounties.geojson", what = "sp")
dataURL<- 'https://afbs.provinz.bz.it/upload/coronavirus/CoronavirusQuarantaene.xlsx'
download.file(dataURL, destfile=temp, mode='wb')
df <- na.omit(readxl::read_excel(temp, sheet =1,skip = 2))

  df$`Cod Istat` <- as.integer(df$`Cod Istat`)
df$ev <- ev
pal <- colorNumeric("viridis", NULL)
       
dataURLp<- 'https://afbs.provinz.bz.it/upload/coronavirus/CoronavirusPositivi.xlsx'
download.file(dataURLp, destfile=temp, mode='wb')

     
dfp <- readxl::read_excel(temp, sheet =1,skip = 2)
# names(dfp)[1]<-paste("x")
# names(dfp)[2]<-paste("y")
# dfp <- subset( dfp, select = -x )
# dfp <- subset( dfp, select = -y )         
names(dfp)[2]<-paste("p")
names(dfp)[3]<-paste("c")

dfp <- na.omit(subset( dfp, select = -c ))
dfp <-  filter(dfp, str_detect(p,'otale'))
names(df)[1]<-paste("astat")
names(dfp)[1]<-paste("astat")
dfp$astat <- as.integer(dfp$astat) 
dfc <-full_join(df, dfp, by = "astat")
names(dfc)[14] <- paste("quis")
names(dfc)[18] <- paste("Totali")
titletext <- paste0("Data Source: Provinz  Bozen <br />  Date : ", Sys.Date(), "<br /> Created with: R by J. Mayr")
labelFormat(prefix = "", suffix = "", between = " – ",
  digits = 3, big.mark = ",", transform = identity)
```
`r titletext`

In die Karte klicken um die Daten zu sehen! 
```{r,echo=FALSE,out.width="100%"}
leaflet(gvcc) %>% 
addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery") %>%
addProviderTiles(providers$CartoDB.Positron)%>%
addLayersControl(baseGroups = c("Carto DB Positron", "World Imagery")) %>%
addPolygons(stroke = F, smoothFactor = 0.1, fillOpacity = .7, fillColor = ~pal(dfc$quis/ev*100),labelOptions = labelOptions(textsize = "15px",opacity = 0.7), label = lapply(paste0("<b>",dfc$Wohngemeinde,"</b> <br />  in Quarantäne in %: ", formatC(dfc$quis/ev*100, big.mark = ","),"<br />  in Quarantäne: ", formatC(dfc$quis, big.mark = ","),"<br /> Änderung: ",  formatC(dfc$`variazione rispetto al giorno precedente...11` , big.mark = ","),"<br /> Positiv: ",  formatC(dfc$Totali , big.mark = ","),"<br /> Änderung: ",  formatC(dfc$`aumento di casi dal giorno prima` , big.mark = ",")), htmltools::HTML)) %>%
addLegend(pal = pal,title = "Quarantäne in % zur EZ",labFormat = labelFormat(),na.label = "Keine Angabe",position = "bottomright", values = ~dfc$quis/ev*100, opacity = .7)#%>% addControl(titletext, position = "topright", className="map-title")

```