---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
 library(leaflet)
  library(curl)
  library(jsonlite)
  library(magrittr)
  library(tibble)
  library(dplyr)
  library(shiny)
  library(ggplot2)
  library(gganimate)
  library(viridis)
library(leaflet.minicharts)

tilesURL <- rgdal::readOGR("https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson")

basemap <- leaflet(width = "100%", height = "400px") %>%
  addTiles(tilesURL)
colors <- c("#3093e5", "#fcba50", "#a0d9e8")
pcmdpcfr <- read.csv(curl("https://github.com/pcm-dpc/COVID-19/raw/master/dati-regioni/dpc-covid19-ita-regioni.csv"))
  pcmdpcr <- filter(pcmdpcfr,pcmdpcfr$lat > 0 & pcmdpcfr$long >0)
  pcmdpcr$data <- as.Date(as.factor(gsub("T.*","",pcmdpcr$data)))
```
In die Karte klicken um die Gemeindedaten zu sehen!
```{r,echo=FALSE,out.width="100%"}
basemap %>% 
  addMinicharts(
    pcmdpcr$long, pcmdpcr$lat, 
    chartdata = pcmdpcr[, c("totale_positivi", "variazione_totale_positivi", "ricoverati_con_sintomi")],
    time = pcmdpcr$data ,
    colorPalette = colors,
    width = 45, height = 45
  )


```